version: "3.8"

services:
  franchise-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchise-service
    ports:
      - "4001:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@franchise-postgres:5432/franchise_db?schema=public
      - PORT=8080
      - NODE_ENV=development
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
    depends_on:
      franchise-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - good-food
    restart: unless-stopped

  franchise-postgres:
    image: postgres:16-alpine
    container_name: franchise-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=franchise_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - good-food

volumes:
  postgres_data:

networks:
  good-food:
    external: true
