apiVersion: apps/v1
kind: Deployment
metadata:
    name: franchise-service
    labels:
        app: franchise-service
spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            app: franchise-service
    template:
        metadata:
            labels:
                app: franchise-service
        spec:
            imagePullSecrets:
                - name: scw-registry-secret
            containers:
                - name: franchise-service
                  image: rg.fr-par.scw.cloud/good-food-container-registry/franchise-service:3b391b72dd588b2dc72f2bb0de04eb2037ae8663
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          memory: "32Mi"
                          cpu: "10m"
                      limits:
                          memory: "64Mi"
                          cpu: "100m"
                  envFrom:
                      - configMapRef:
                            name: franchise-service-config
                      - secretRef:
                            name: franchise-service-db-secret
                      - secretRef:
                            name: good-food-jwt-secret
                      - secretRef:
                            name: rabbitmq-secret
---
apiVersion: v1
kind: Service
metadata:
    name: franchise-service
spec:
    selector:
        app: franchise-service
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: franchise-service-config
data:
    NODE_ENV: "production"
    PORT: "8080"
